Core/books/urls.py
from django.urls import path
from .views import IndexView, BookDetailsView, BookListView, AddBookView, EditBookView, BookListViewExtra, DataTable, TableView

app_name = 'books'

urlpatterns = [
    #path('', IndexView.as_view(), name="books"),
    path('', BookListView.as_view(), name="book_list"),
    path('table/view', TableView.as_view(), name="book_table"),
    path('table/list', DataTable.as_view(), name="book_table_list"),
    path('add/', AddBookView.as_view(), name="book_add"),
    path('<slug:slug>/', BookDetailsView.as_view(), name="book-detail"),
    path('<slug:slug>/edit/', EditBookView.as_view(), name="book_edit"),
]

Core/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Core.users.urls')),
    path('posts/', include('Core.posts.urls')),
    path('books/', include('Core.books.urls', namespace='books')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/books/models.py
from django.db import models
from django.template.defaultfilters import slugify

class Book(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField(null=True)
    description = models.TextField()
    author = models.TextField(null=True)
    count = models.IntegerField(null=True, default=0)
    coverpage = models.FileField(null=True, upload_to = "coverpage/")
    
    class Meta:
        ordering = ('-id', )

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def get_title(self):
        return "abul Kashem" + self.title

Core/books/forms.py
from django import forms
from .models import Book


class AddForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'description', 'author', 'coverpage')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'coverpage': forms.FileInput(attrs={'class': 'form-control'}),
        }

Core/books/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, CreateView, UpdateView
from django.utils import timezone

from .models import Book
from .forms import AddForm
from django.db.models import Q
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django_redis import get_redis_connection
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import PermissionRequiredMixin

from django.core import serializers
from django.http import JsonResponse

class IndexView(TemplateView):
    template_name = "book/home.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Book.objects.all()
        return context

#FormView
"""
class AddBookView(FormView):
    template_name = "book/book_add.html"
    form_class = AddForm
    success_url = '/books/'


    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

"""
#Createview , we don't need to form validate in create view.
class AddBookView(CreateView):
    model = Book
    template_name = "book/book_add.html"
    form_class = AddForm
    success_url = '/books/'


    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(**kwargs)
        initial['title'] = 'enter Title'
        return initial



class EditBookView(PermissionRequiredMixin, UpdateView):
    permission_required = 'books.change_books' # ('books.change_books', 'books.add_books')
    model = Book
    template_name = "book/book_edit.html"
    form_class = AddForm
    success_url = '/books/'

class BookDetailsView(DetailView):
    model = Book
    template_name = "book/book-details.html"
    context_object_name = "book"
    #if we not define context object name we can access ta through object.title or ect

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        books = Book.objects.filter(slug=self.kwargs.get('slug'))
        context['time'] = timezone.now()
        return context

#@method_decorator(cache_page(60 * 5), name='dispatch')
class BookListView(ListView):
    model = Book
    template_name = "book/list.html"
    context_object_name = "books"
    paginate_by = 5

    """
    def get_queryset(self): #method to change the list of records returned
        return Book.objects.all()
    """
    def get_context_data(self, **kwargs):  #in order to pass additional context variables
        context = super().get_context_data(**kwargs)
        #context['books'] = Book.objects.all()[:2]
        return context

    def get_queryset(self, *args, **kwargs):
        title = self.kwargs.get('title')
        print(args)
        print(title)
        if title:
            return Book.objects.filter(title__icontains=self.kwargs.get('title')) #__icontains for case sensitive search
        context = super().get_queryset(*args, **kwargs)
        return context

class BookListViewExtra(ListView):
    model = Book
    template_name = "book/list.html"
    context_object_name = "books"     #default object_list
    paginate_by = 4
    #queryset = Book.objects.all()[:2]
    #or method

    def get_queryset(self, *args, **kwargs):
        print(self.kwargs.get('title'))
        return Book.objects.filter(title__icontains=self.kwargs.get('title')) #__icontains for case sensitive search


class TableView(TemplateView):
    template_name = "book/datatable.html"

class DataTable(ListView):
    model = Book
    template_name = "book/ajax.html"
    context_object_name = "books"
    paginate_by = 10

    def get_queryset(self, *args, **kwargs):
        search = self.request.GET.get('search', '')
        if search:
            return Book.objects.filter(Q(title__icontains=search) | Q(description__icontains=search)).distinct() #__icontains for case sensitive search
        return super().get_queryset(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get('page')
        limit = self.request.GET.get('limit')
        _sl = 1
        _lm = 10
        if page:
            _sl = int(page)
        if limit:
            _lm = int(limit)
        context['sl_count'] = (_sl * _lm - (_lm - 1)) - 1

        return context

    def get_paginate_by(self, queryset):
        return self.request.GET.get('limit', self.paginate_by)

    def get_ordering(self):
        ordering = self.request.GET.get('order_by', 'id')
        return ordering

templates/book/ajax.html
{% for book in books %}
<tr>
    <td>{{ forloop.counter0 | add:page_obj.start_index  }}</td>
    <td>{{ book.id }}</td>
    <td>{{ book.title }}</td>
    <td>{{ book.description }}</td>
</tr>
{% endfor %}
<tr>
    <td colspan="4">
        <div class="float-left">
            Showing {{ page_obj.start_index }} to {{ page_obj.end_index  }} of {{ page_obj.paginator.count }} entries
        </div>
        <ul class="pagination float-right" role="navigation">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" rel="prev" aria-label="« Previous">‹</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page=1">Frist</a>
                </li>                
            {% else %}
                <li class="page-item disabled" aria-disabled="true" aria-label="« Previous">
                    <span class="page-link" aria-hidden="true">‹</span>
                </li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active" aria-current="page"><span class="page-link">{{ i }}</span></li>
                
                {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            </li>            
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" rel="next" aria-label="Next »">›</a>
                </li>
            {% else %}
                <li class="page-item disabled" aria-disabled="true" aria-label="Next »">
                    <span class="page-link" aria-hidden="true">›</span>
                </li>
            {% endif %}
        </ul>
    </td>
</tr>

templates/book/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>{% block title %} Welcome to Books {% endblock %}</title>
</head>

<body>
    {% block content %}
    {% endblock %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha512-+NqPlbbtM1QqiK8ZAo4Yrj2c4lNQoGv8P79DPtKzj++l5jnN39rHA/xsqn8zE9l0uSoxaCdrOgFs6yjyfbBxSg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>

    {% block scripts %}
    {%endblock %}
</body>

</html>

templates/book/book-details.html

    {% extends "book/base.html" %}
    {% block content %}
    <div class="container" style="max-width:800px">
        <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">{{book.title}}</h1>
            <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{book.genre}}</small>
                <small class="text-muted">{{book.isbn}}</small>
                <small class="text-muted">{{time}}</small>
            </div>
        </div>

    </div>
    {% endblock %}

templates/book/book_add.html
{% extends "book/base.html" %}
{% block content %}
<div class="container" style="max-width:600px">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">All Books</h1>
        <p class="lead">A range of wonderful programming books to help you learn JavaScript.</p>
    </div>
    <div class="py-5">
        <div class="row">
            <div class="col-12">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/book/book_edit.html
{% extends "book/base.html" %}
{% block content %}
<div class="container" style="max-width:600px">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">All Books</h1>
        <p class="lead">A range of wonderful programming books to help you learn JavaScript.</p>
    </div>
    <div class="py-5">
        <div class="row">
            <div class="col-12">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/book/datatable.html
{% extends "book/base.html" %}
{% block content %}
<div class="container">
    <div class="py-5">
        <div class="row mb-3">
            <div class="col-md-6">
                <div class="float-left">
                    <div class="input-group">
                        <select id="limit" class="form-control" >
                            <option value="2" selected>2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="10">10</option>
                            <option value="20">20</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="float-right">
                        <div class="input-group">
                            <input type="text" name="search" placeholder="Search" id="search_key" class="form-control">
                            <div class="input-group-btn">
                                <button class="btn btn-info" type="submit">
                                    Search
                                </button>
                            </div>
                        </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <table class="table table-hover table-striped table-bordered text-center" id="leaderTable">
                    <thead>
                        <tr>
                            <th>#SL</th>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block scripts %}
<script>
    $("#leaderTable").on("click",'.pagination li a',function () {
        var page_url=$(this).attr("href");
        if(page_url=="javascript:void(0)"){
            return false;
        }
        get_view(page_url);
        return false;
    });
    $("#search_key").on("change",function () {
        get_view(false);
        return false;
    });
    $("#limit").on("change",function () {
        get_view(false);
        return false;
    });

    get_view(false);

    function get_view(page_url){
        var limit=$("#limit").val();
        var search_key=$("#search_key").val();
        var base_url="{% url 'books:book_table_list' %}";
        if(page_url){
            base_url = base_url + page_url;
        }
        $.ajax({
            url:base_url,
            type:"get",
            data:{
                "limit": limit,
                "search": search_key
            },
            success:function(data){
                $("#leaderTable tbody").html(data);
            },
            error:function (e) {
                alert("error")
            }
        });
    }
</script>

{% endblock %}

templates/book/home.html
{% extends "book/base.html" %}
{% block content %}
<div class="container">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">All Books</h1>
        <p class="lead">A range of wonderful programming books to help you learn JavaScript.</p>
    </div>
    <div class="py-5">
        <div class="row">
            {% for book in books %}
            <div class="col-md-4">
                <a class="text-dark" href="{% url 'books:book-detail' slug=book.slug %}">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
                                {{book.title|truncatechars:50}}</h2>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{book.genre}}</small>
                                <small class="text-muted">{{book.isbn}}</small>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/book/list.html
{% extends "book/base.html" %}
{% load thumbnail %}
{% block content %}
<div class="container">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">All Books</h1>
        <p class="lead">A range of wonderful programming books to help you learn JavaScript.</p>
    </div>
    <div class="py-5">
        <div class="row">
            {% for book in books %}
            <h1>{{ book.get_title }}</h1>
            <div class="col-md-4">
                <a class="text-dark" href="{% url 'books:book-detail' slug=book.slug %}">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
                                {{book.title|truncatechars:50}}</h2>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{book.genre}}</small>
                                <small class="text-muted">{{book.isbn}}</small>
                            </div>
                        </div>
                    </div>
                </a>
                {% if book.coverpage %}
                    {% thumbnail book.coverpage "800x800" crop="center" as im %}
                        <img src="{{ im.url }}" height="200px"/>
                    {% endthumbnail %}
                {% endif %}
            </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col-12">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
            
                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
            
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>

    </div>
</div>
{% endblock %}